### ISSUE TITLE
support for Wii MotionPlus

### ISSUE THREAD

**Issue by dglaude** [adafruit/Adafruit_CircuitPython_Nunchuk#19]
The Wii MotionPlus is an addon for the Wii Mote (latter this was build-in into the Wii Mote).
It is "pass-through" I2C on the Wii Mote so that you can connect your Nunchuck after that.
It does add gyroscope to the Wii Mote build-in accelerator and this enhance the precision of move detection.
Communication with the MotionPlus is I2C but not on the same address as other accessories.
They are pretty cheap in second hand shop.
With a bit of software it is a nice gyroscope.
I'll try solving this issue as I have two.

**Comment by caternuson** [comment]
For now, let's keep this library as Nunchuk only. Maybe in the future it will grow to include more items.

But this definitely looks like something that could get added to the eventual Community Bundle version:
https://github.com/adafruit/Adafruit_CircuitPython_Nunchuk/pull/25#issuecomment-772895034
which will include multiple *chuk accessories.
