### ISSUE TITLE
Some of the examples are out of date

### ISSUE THREAD

**Issue by hamslabs** [adafruit/Adafruit_CircuitPython_Nunchuk#26]
The example programs have some errors and it looks like they are out of date.
#1 They use Nunchuk.button_C rather than Nunchuk.buttons.C  (same for button Z)
#2 The initialization for the mouse doesn't use usb_hid.devices and usb_hid is not imported.

I'd fix it and do a pull request but it's probably be easier for both of us this way.

**Comment by hamslabs** [comment]
The documentation at readthedocs for this reflects the older code as well.

**Comment by caternuson** [comment]
You are linking to old closed issue threads. Any code examples you find there may be wrong, out of date, incomplete, etc.

If you are using the latest library release, then you should be able to use the examples found in the `examples` folder of this repo:
https://github.com/adafruit/Adafruit_CircuitPython_Nunchuk/tree/main/examples
They have been updated as needed to use the current library API.

**Comment by hamslabs** [comment]
Ahh, I did have an out of date version of the Bundle, sorry about that. I double checked the documentation and it's still the old version:
https://circuitpython.readthedocs.io/projects/nunchuk/en/latest/api.html

**Comment by caternuson** [comment]
OK, I'm seeing same thing with the read the docs link. Will look into that.

**Comment by caternuson** [comment]
Docs should be fixed now as well. We changed the name of the base branch from `master` to `main` and that broke some things on the documentation system. Just needed to change there as well and now it appears to be all good.
